# Generated by Django 3.2.4 on 2024-05-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_ulbipl', upload_to='images/'),
        ),
    ]
